### ISSUE TITLE
Unable to get property 'ticking' of undefined or null reference

### ISSUE THREAD

**Issue by romain-granai** [chartjs/chartjs-plugin-deferred#8] opened 2018-01-22 13:59 UTC
Hi,

I have this error logged on IE11. Does someone knows what might cause this error?

Thank you.

**Comment by simonbrunel** [comment] 2018-01-22 14:09
I can't reproduce this issue with IE11 / Chart.js 2.7.1 / chartjs-plugin-deferred 1.0.0. Isn't it a duplicate of #6? If not, please provide the link to the page (or a jsfiddle) that reproduces this issue, plus the versions of Chart.js and this plugin you are using.

**Comment by simonbrunel** [comment] 2018-02-07 18:39
@romain-granai any update?

**Comment by romain-granai** [comment] 2018-02-08 17:28
Hi Simon,

Sorry for late answer. I haven't worked on my project for a while, but as far as I remember the log was showing on the compatibility mode of ie11, our client was forcing the compatibility mode for some reasons. So you might be able to reproduce the issue like that, however I don't think it was breaking anything.

Hope it helped.

**Comment by fitzy90** [comment] 2018-03-02 13:11
I just proposed a small change that corrects the ticking issue and works in all browsers for me?

**Comment by simonbrunel** [comment] 2018-03-21 12:24
Released in [1.0.1](/chartjs/chartjs-plugin-deferred/releases/tag/v1.0.1)

**Closed by simonbrunel** 2018-03-21 12:24 UTC
Labels: bug
